name: Segmentation Models

on: [push]

jobs:
  model_generation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install python libs
      run: pip install -r requirements.txt
    
    - name: Run test script
      run: python test.py